services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\CleanupBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaCleanupBundle.php'
