services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\CleanupBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaCleanupBundle.php'

    # alias used in CleanupPass
    oh_media_cleanup.command: '@OHMedia\CleanupBundle\Command\CleanupCommand'
